fix: correct update_git_completions func & update git completions

diff --git a/functions/update_git_completions b/functions/update_git_completions
--- a/functions/update_git_completions
+++ b/functions/update_git_completions
@@ -1,12 +1,13 @@
 #!/bin/zsh
 function update_git_completions {
   emulate -L zsh
-  # Download the git scripts
-  echo "Generating git completions..."
   local giturl=https://raw.githubusercontent.com/git/git/master/contrib/completion
-  local dest=${1:-$ZSH_CUSTOM/plugins/git/completions}
+  local dest=${1:-${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/completions}
   [[ -d $dest ]] || mkdir -p $dest
-  curl -fsSL $giturl/git-completion.bash -o $dest/git-completion.bash
-  curl -fsSL $giturl/git-completion.zsh -o $dest/_git
+  echo "Updating git completions in $dest ..."
+  curl -fsSL $giturl/git-completion.bash -o $dest/git-completion.bash \
+    && curl -fsSL $giturl/git-completion.zsh -o $dest/_git \
+    && echo "Done. Restart your shell or run 'compinit' to pick up changes." \
+    || echo "Failed to download git completions."
 }
 update_git_completions "$@"
